# Generated by Django 4.1.7 on 2023-03-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('D', 'Driver'), ('I', 'Irons'), ('W', 'Wedge'), ('P', 'Putter')], max_length=1)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
